version: '3'

services:
  rabbitmq:
    build: ./rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
  mongodb:
    image: mongo:3.6
  redis:
    image: redis:4.0-alpine
  postgres:
    image: postgres:10.3-alpine
    