FROM rabbitmq:3.7-alpine

RUN rabbitmq-plugins enable rabbitmq_event_exchange
RUN rabbitmq-plugins enable rabbitmq_amqp1_0
RUN rabbitmq-plugins enable rabbitmq_management
RUN rabbitmq-plugins enable rabbitmq_stomp
RUN rabbitmq-plugins enable rabbitmq_web_stomp